openapi: 3.0.0
info:
  title: Objeto API
  description: API para manejar objetos con `user_id`, `nombre`, y `valor`.
  version: 1.0.0
servers:
  - url: http://owncollector.mainu.com.mx

paths:
  /objetos:
    post:
      summary: Crear un nuevo objeto
      description: Endpoint para crear un nuevo objeto en el sistema.
      tags:
        - Objetos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - nombre
                - valor
              properties:
                user_id:
                  type: integer
                  example: 1
                  description: ID del usuario al que pertenece el objeto.
                nombre:
                  type: string
                  example: "Ejemplo de Objeto"
                  description: Nombre del objeto.
                valor:
                  type: number
                  format: float
                  example: 99.99
                  description: Valor del objeto.
      responses:
        201:
          description: Objeto creado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Datos Registrados"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      user_id:
                        type: integer
                        example: 1
                      nombre:
                        type: string
                        example: "Ejemplo de Objeto"
                      valor:
                        type: number
                        format: float
                        example: 99.99
                      created_at:
                        type: string
                        format: date-time
                        example: "2024-12-01T00:00:00Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2024-12-01T00:00:00Z"
        400:
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Faltan datos requeridos"
